#ifndef SYSCALLS_H
#define SYSCALLS_H

#define SYSCALL_exit		  1
#define SYSCALL_fork		  2
#define SYSCALL_read		  3
#define SYSCALL_write		  4
#define SYSCALL_open		  5
#define SYSCALL_close		  6
#define SYSCALL_waitpid		  7
#define SYSCALL_creat		  8
#define SYSCALL_link		  9
#define SYSCALL_unlink		 10
#define SYSCALL_execve		 11
#define SYSCALL_chdir		 12
#define SYSCALL_time		 13
#define SYSCALL_mknod		 14
#define SYSCALL_chmod		 15
#define SYSCALL_lchown		 16
#define SYSCALL_break		 17
#define SYSCALL_oldstat		 18
#define SYSCALL_lseek		 19
#define SYSCALL_getpid		 20
#define SYSCALL_mount		 21
#define SYSCALL_umount		 22
#define SYSCALL_setuid		 23
#define SYSCALL_getuid		 24
#define SYSCALL_stime		 25
#define SYSCALL_ptrace		 26
#define SYSCALL_alarm		 27
#define SYSCALL_oldfstat	 28
#define SYSCALL_pause		 29
#define SYSCALL_utime		 30
#define SYSCALL_stty		 31
#define SYSCALL_gtty		 32
#define SYSCALL_access		 33
#define SYSCALL_nice		 34
#define SYSCALL_ftime		 35
#define SYSCALL_sync		 36
#define SYSCALL_kill		 37
#define SYSCALL_rename		 38
#define SYSCALL_mkdir		 39
#define SYSCALL_rmdir		 40
#define SYSCALL_dup		 41
#define SYSCALL_pipe		 42
#define SYSCALL_times		 43
#define SYSCALL_prof		 44
#define SYSCALL_brk		 45
#define SYSCALL_setgid		 46
#define SYSCALL_getgid		 47
#define SYSCALL_signal		 48
#define SYSCALL_geteuid		 49
#define SYSCALL_getegid		 50
#define SYSCALL_acct		 51
#define SYSCALL_umount2		 52
#define SYSCALL_lock		 53
#define SYSCALL_ioctl		 54
#define SYSCALL_fcntl		 55
#define SYSCALL_mpx		 56
#define SYSCALL_setpgid		 57
#define SYSCALL_ulimit		 58
#define SYSCALL_oldolduname	 59
#define SYSCALL_umask		 60
#define SYSCALL_chroot		 61
#define SYSCALL_ustat		 62
#define SYSCALL_dup2		 63
#define SYSCALL_getppid		 64
#define SYSCALL_getpgrp		 65
#define SYSCALL_setsid		 66
#define SYSCALL_sigaction	 67
#define SYSCALL_sgetmask	 68
#define SYSCALL_ssetmask	 69
#define SYSCALL_setreuid	 70
#define SYSCALL_setregid	 71
#define SYSCALL_sigsuspend	 72
#define SYSCALL_sigpending	 73
#define SYSCALL_sethostname	 74
#define SYSCALL_setrlimit	 75
#define SYSCALL_getrlimit	 76	/* Back compatible 2Gig limited rlimit */
#define SYSCALL_getrusage	 77
#define SYSCALL_gettimeofday	 78
#define SYSCALL_settimeofday	 79
#define SYSCALL_getgroups	 80
#define SYSCALL_setgroups	 81
#define SYSCALL_select		 82
#define SYSCALL_symlink		 83
#define SYSCALL_oldlstat	 84
#define SYSCALL_readlink	 85
#define SYSCALL_uselib		 86
#define SYSCALL_swapon		 87
#define SYSCALL_reboot		 88
#define SYSCALL_readdir		 89
#define SYSCALL_mmap		 90
#define SYSCALL_munmap		 91
#define SYSCALL_truncate	 92
#define SYSCALL_ftruncate	 93
#define SYSCALL_fchmod		 94
#define SYSCALL_fchown		 95
#define SYSCALL_getpriority	 96
#define SYSCALL_setpriority	 97
#define SYSCALL_profil		 98
#define SYSCALL_statfs		 99
#define SYSCALL_fstatfs		100
#define SYSCALL_ioperm		101
#define SYSCALL_socketcall	102
#define SYSCALL_syslog		103
#define SYSCALL_setitimer	104
#define SYSCALL_getitimer	105
#define SYSCALL_stat		106
#define SYSCALL_lstat		107
#define SYSCALL_fstat		108
#define SYSCALL_olduname	109
#define SYSCALL_iopl		110
#define SYSCALL_vhangup		111
#define SYSCALL_idle		112
#define SYSCALL_vm86old		113
#define SYSCALL_wait4		114
#define SYSCALL_swapoff		115
#define SYSCALL_sysinfo		116
#define SYSCALL_ipc		117
#define SYSCALL_fsync		118
#define SYSCALL_sigreturn	119
#define SYSCALL_clone		120
#define SYSCALL_setdomainname	121
#define SYSCALL_uname		122
#define SYSCALL_modify_ldt	123
#define SYSCALL_adjtimex	124
#define SYSCALL_mprotect	125
#define SYSCALL_sigprocmask	126
#define SYSCALL_create_module	127
#define SYSCALL_init_module	128
#define SYSCALL_delete_module	129
#define SYSCALL_get_kernel_syms	130
#define SYSCALL_quotactl	131
#define SYSCALL_getpgid		132
#define SYSCALL_fchdir		133
#define SYSCALL_bdflush		134
#define SYSCALL_sysfs		135
#define SYSCALL_personality	136
#define SYSCALL_afs_		137 /*  for Andrew File System */
#define SYSCALL_setfsuid	138
#define SYSCALL_setfsgid	139
#define SYSCALL__llseek		140
#define SYSCALL_getdents	141
#define SYSCALL__newselect	142
#define SYSCALL_flock		143
#define SYSCALL_msync		144
#define SYSCALL_readv		145
#define SYSCALL_writev		146
#define SYSCALL_getsid		147
#define SYSCALL_fdatasync	148
#define SYSCALL__sysctl		149
#define SYSCALL_mlock		150
#define SYSCALL_munlock		151
#define SYSCALL_mlockall	152
#define SYSCALL_munlockall	153
#define SYSCALL_sched_setparam	154
#define SYSCALL_sched_getparam	155
#define SYSCALL_sched_setscheduler	156
#define SYSCALL_sched_getscheduler	157
#define SYSCALL_sched_yield		158
#define SYSCALL_sched_get_priority_max	159
#define SYSCALL_sched_get_priority_min	160
#define SYSCALL_sched_rr_get_interval	161
#define SYSCALL_nanosleep		162
#define SYSCALL_mremap		163
#define SYSCALL_setresuid	164
#define SYSCALL_getresuid	165
#define SYSCALL_vm86		166
#define SYSCALL_query_module	167
#define SYSCALL_poll		168
#define SYSCALL_nfsservctl	169
#define SYSCALL_setresgid	170
#define SYSCALL_getresgid	171
#define SYSCALL_prctl           172
#define SYSCALL_rt_sigreturn	173
#define SYSCALL_rt_sigaction	174
#define SYSCALL_rt_sigprocmask	175
#define SYSCALL_rt_sigpending	176
#define SYSCALL_rt_sigtimedwait	177
#define SYSCALL_rt_sigqueueinfo	178
#define SYSCALL_rt_sigsuspend	179
#define SYSCALL_pread		180
#define SYSCALL_pwrite		181
#define SYSCALL_chown		182
#define SYSCALL_getcwd		183
#define SYSCALL_capget		184
#define SYSCALL_capset		185
#define SYSCALL_sigaltstack	186
#define SYSCALL_sendfile	187
#define SYSCALL_getpmsg		188	/* some people actually want streams */
#define SYSCALL_putpmsg		189	/* some people actually want streams */
#define SYSCALL_vfork		190
#define SYSCALL_ugetrlimit	191	/* SuS compliant getrlimit */
#define SYSCALL_mmap2		192
#define SYSCALL_truncate64	193
#define SYSCALL_ftruncate64	194
#define SYSCALL_stat64		195
#define SYSCALL_lstat64		196
#define SYSCALL_fstat64		197
#define SYSCALL_lchown32	198
#define SYSCALL_getuid32	199
#define SYSCALL_getgid32	200
#define SYSCALL_geteuid32	201
#define SYSCALL_getegid32	202
#define SYSCALL_setreuid32	203
#define SYSCALL_setregid32	204
#define SYSCALL_getgroups32	205
#define SYSCALL_setgroups32	206
#define SYSCALL_fchown32	207
#define SYSCALL_setresuid32	208
#define SYSCALL_getresuid32	209
#define SYSCALL_setresgid32	210
#define SYSCALL_getresgid32	211
#define SYSCALL_chown32		212
#define SYSCALL_setuid32	213
#define SYSCALL_setgid32	214
#define SYSCALL_setfsuid32	215
#define SYSCALL_setfsgid32	216
#define SYSCALL_pivot_root	217
#define SYSCALL_mincore		218
#define SYSCALL_madvise		219
#define SYSCALL_madvise1	219	/* delete when C lib stub is removed */
#define SYSCALL_getdents64	220
#define SYSCALL_fcntl64		221
/* 223 is unused */
#define SYSCALL_gettid		224
#define SYSCALL_readahead	225
#define SYSCALL_setxattr	226
#define SYSCALL_lsetxattr	227
#define SYSCALL_fsetxattr	228
#define SYSCALL_getxattr	229
#define SYSCALL_lgetxattr	230
#define SYSCALL_fgetxattr	231
#define SYSCALL_listxattr	232
#define SYSCALL_llistxattr	233
#define SYSCALL_flistxattr	234
#define SYSCALL_removexattr	235
#define SYSCALL_lremovexattr	236
#define SYSCALL_fremovexattr	237
#define SYSCALL_tkill		238
#define SYSCALL_sendfile64	239
#define SYSCALL_futex		240
#define SYSCALL_sched_setaffinity	241
#define SYSCALL_sched_getaffinity	242
#define SYSCALL_set_thread_area	243
#define SYSCALL_get_thread_area	244
#define SYSCALL_io_setup	245
#define SYSCALL_io_destroy	246
#define SYSCALL_io_getevents	247
#define SYSCALL_io_submit	248
#define SYSCALL_io_cancel	249
#define SYSCALL_fadvise64	250

#define SYSCALL_exit_group	252
#define SYSCALL_lookup_dcookie	253
#define SYSCALL_epoll_create	254
#define SYSCALL_epoll_ctl	255
#define SYSCALL_epoll_wait	256
#define SYSCALL_remap_file_pages257
#define SYSCALL_set_tid_address	258
#define SYSCALL_timer_create	259
#define SYSCALL_timer_settime		(SYSCALL_timer_create+1)
#define SYSCALL_timer_gettime		(SYSCALL_timer_create+2)
#define SYSCALL_timer_getoverrun	(SYSCALL_timer_create+3)
#define SYSCALL_timer_delete		(SYSCALL_timer_create+4)
#define SYSCALL_clock_settime		(SYSCALL_timer_create+5)
#define SYSCALL_clock_gettime		(SYSCALL_timer_create+6)
#define SYSCALL_clock_getres		(SYSCALL_timer_create+7)
#define SYSCALL_clock_nanosleep		(SYSCALL_timer_create+8)
#define SYSCALL_statfs64	268
#define SYSCALL_fstatfs64	269
#define SYSCALL_tgkill		270
#define SYSCALL_utimes		271
#define SYSCALL_fadvise64_64	272
#define SYSCALL_vserver		273
#define SYSCALL_mbind		274
#define SYSCALL_get_mempolicy	275
#define SYSCALL_set_mempolicy	276
#define SYSCALL_mq_open 	277
#define SYSCALL_mq_unlink	(SYSCALL_mq_open+1)
#define SYSCALL_mq_timedsend	(SYSCALL_mq_open+2)
#define SYSCALL_mq_timedreceive	(SYSCALL_mq_open+3)
#define SYSCALL_mq_notify	(SYSCALL_mq_open+4)
#define SYSCALL_mq_getsetattr	(SYSCALL_mq_open+5)
#define SYSCALL_sys_kexec_load	283
#define SYSCALL_waitid		284
/* #define SYSCALL_sys_setaltroot	285 */
#define SYSCALL_add_key		286
#define SYSCALL_request_key	287
#define SYSCALL_keyctl		288
#define SYSCALL_ioprio_set	289
#define SYSCALL_ioprio_get	290
#define SYSCALL_inotify_init	291
#define SYSCALL_inotify_add_watch	292
#define SYSCALL_inotify_rm_watch	293

#endif
